version: '3'

services:
  app:
    build: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask_app"
      - "traefik.backend.healthcheck.path=/health"
      - "traefik.backend.healthcheck.interval=1s"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=8000"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_webgateway