version: '3'

services:
  app:
    image: marcuslind90/digitalocean-terraform-docker:bfc5a54e
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.15
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
