version: '3'

services:
  app:
    image: marcuslind90/digitalocean-terraform-docker:411d0c6a
    restart: always

  nginx:
    image: nginx:1.15
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
