version: '3'

services:
  app:
    image: marcuslind90/digitalocean-terraform-docker:27033528
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.15
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
